package ProyectoCalculadora;

import java.util.ArrayList;

public class Vista extends javax.swing.JFrame {
	public String expresio;

	/**
	 * Creates new form Vista
	 */
	public Vista() {
		initComponents();
		expresio = "";
		// Pantalla.setAlignment(javax.swing.JTextField.RIGHT);

	}

	/**
	 * expresio= " "; }
	 * 
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		div = new javax.swing.JButton();
		parentesis2 = new javax.swing.JButton();
		parentesis1 = new javax.swing.JButton();
		AC = new javax.swing.JButton();
		mult = new javax.swing.JButton();
		nueve = new javax.swing.JButton();
		ocho = new javax.swing.JButton();
		siete = new javax.swing.JButton();
		menos = new javax.swing.JButton();
		seis = new javax.swing.JButton();
		cinco = new javax.swing.JButton();
		cuatro = new javax.swing.JButton();
		mas = new javax.swing.JButton();
		tres = new javax.swing.JButton();
		dos = new javax.swing.JButton();
		uno = new javax.swing.JButton();
		igual = new javax.swing.JButton();
		coma = new javax.swing.JButton();
		cero = new javax.swing.JButton();
		potencia = new javax.swing.JButton();
		Pantalla = new java.awt.TextField();

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));
		setBounds(new java.awt.Rectangle(0, 0, 0, 0));
		setForeground(new java.awt.Color(0, 0, 0));

		div.setBackground(new java.awt.Color(0, 153, 0));
		div.setText("/");
		div.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				divActionPerformed(evt);
			}
		});

		parentesis2.setBackground(new java.awt.Color(204, 204, 204));
		parentesis2.setText(")");
		parentesis2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				parentesis2ActionPerformed(evt);
			}
		});

		parentesis1.setBackground(new java.awt.Color(204, 204, 204));
		parentesis1.setText("(");
		parentesis1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				parentesis1ActionPerformed(evt);
			}
		});

		AC.setBackground(new java.awt.Color(204, 204, 204));
		AC.setText("AC");
		AC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ACActionPerformed(evt);
			}
		});

		mult.setBackground(new java.awt.Color(0, 153, 0));
		mult.setText("x");
		mult.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				multActionPerformed(evt);
			}
		});

		nueve.setBackground(new java.awt.Color(102, 102, 102));
		nueve.setText("9");
		nueve.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nueveActionPerformed(evt);
			}
		});

		ocho.setBackground(new java.awt.Color(102, 102, 102));
		ocho.setText("8");
		ocho.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ochoActionPerformed(evt);
			}
		});

		siete.setBackground(new java.awt.Color(102, 102, 102));
		siete.setText("7");
		siete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sieteActionPerformed(evt);
			}
		});

		menos.setBackground(new java.awt.Color(0, 153, 0));
		menos.setText("-");
		menos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menosActionPerformed(evt);
			}
		});

		seis.setBackground(new java.awt.Color(102, 102, 102));
		seis.setText("6");
		seis.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				seisActionPerformed(evt);
			}
		});

		cinco.setBackground(new java.awt.Color(102, 102, 102));
		cinco.setText("5");
		cinco.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cincoActionPerformed(evt);
			}
		});

		cuatro.setBackground(new java.awt.Color(102, 102, 102));
		cuatro.setText("4");
		cuatro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cuatroActionPerformed(evt);
			}
		});

		mas.setBackground(new java.awt.Color(0, 153, 0));
		mas.setText("+");
		mas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				masActionPerformed(evt);
			}
		});

		tres.setBackground(new java.awt.Color(102, 102, 102));
		tres.setText("3");
		tres.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tresActionPerformed(evt);
			}
		});

		dos.setBackground(new java.awt.Color(102, 102, 102));
		dos.setText("2");
		dos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dosActionPerformed(evt);
			}
		});

		uno.setBackground(new java.awt.Color(102, 102, 102));
		uno.setText("1");
		uno.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				unoActionPerformed(evt);
			}
		});

		igual.setBackground(new java.awt.Color(0, 153, 0));
		igual.setText("=");
		igual.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				igualActionPerformed(evt);
			}
		});

		coma.setBackground(new java.awt.Color(204, 204, 204));
		coma.setText(".");
		coma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comaActionPerformed(evt);
			}
		});

		cero.setBackground(new java.awt.Color(102, 102, 102));
		cero.setText("0");
		cero.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ceroActionPerformed(evt);
			}
		});

		potencia.setBackground(new java.awt.Color(204, 204, 204));
		potencia.setText("^");
		potencia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				potenciaActionPerformed(evt);
			}
		});

		Pantalla.setText(expresio);
		Pantalla.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PantallaActionPerformed(evt);
			}
		});
		Pantalla.addTextListener(new java.awt.event.TextListener() {
			public void textValueChanged(java.awt.event.TextEvent evt) {
				PantallaTextValueChanged(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addGap(0, 26, Short.MAX_VALUE).addComponent(Pantalla,
								javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(43, 43, 43)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(uno).addComponent(cuatro).addComponent(siete)))
								.addGroup(layout.createSequentialGroup().addGap(26, 26, 26).addComponent(AC,
										javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(42, 42, 42).addComponent(cero)))
								.addGap(70, 70, 70)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(cinco).addComponent(dos).addComponent(ocho)
										.addComponent(parentesis1).addComponent(potencia))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(nueve, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(parentesis2, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(seis, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(tres, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(coma, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(85, 85, 85)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(mas, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(menos, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(mult, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(igual, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(div, javax.swing.GroupLayout.Alignment.TRAILING))))
				.addContainerGap(22, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(23, 23, 23)
				.addComponent(
						Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(20, 20, 20)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(div)
						.addComponent(parentesis2).addComponent(parentesis1).addComponent(AC))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(mult)
						.addComponent(nueve).addComponent(ocho).addComponent(siete))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(menos)
						.addComponent(seis).addComponent(cinco).addComponent(cuatro))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(mas)
						.addComponent(tres).addComponent(dos).addComponent(uno))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(igual)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cero).addComponent(potencia).addComponent(coma)))
				.addContainerGap(9, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void divActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "/";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void multActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "*";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void ochoActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "8";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	// Metodo auxiliar para identificar operadores.
	private static boolean checarOperador(char c) {
		boolean resp = false;
		if (c == '+' || c == '-' || c == '*' || c == '/' || c == '^')
			resp = true;
		return resp;
	}

	private static boolean checarParentesis(char c) {
		boolean resp = false;
		if (c == '(' || c == ')')
			resp = true;
		return resp;
	}

	private void igualActionPerformed(java.awt.event.ActionEvent evt) {
		ArrayList<String> list = new ArrayList<String>();
		RevisorSintaxis b = new RevisorSintaxis(expresio);
		if (b.isSyntaxOk()) {
			int i = 0;
			while (i < expresio.length()) {
				StringBuilder sb = new StringBuilder();
				if(i==0 && expresio.charAt(i)=='-') {
					list.add("0");
				}
				if(i>0 && expresio.charAt(i)=='-' && expresio.charAt(i-1)=='(' || i>0 && expresio.charAt(i)=='-' && expresio.charAt(i-1)=='*') {
					list.add("0");
				}
				if(checarOperador(expresio.charAt(i)) || checarParentesis(expresio.charAt(i))) {
					sb.append(expresio.charAt(i));
				}
				int j = i;
				while (j < expresio.length() && !checarOperador(expresio.charAt(j))
						&& !checarParentesis(expresio.charAt(j))) {
					sb.append(expresio.charAt(j));
					j++;

				}
				list.add(sb.toString());
				sb = new StringBuilder();
				if (j > i) {
					i = j;
				} else {
					i++;
				}
			}
			System.out.println(list.toString());
			try {
				double resp = InfijoAPosfijo.evaluaPostfijo(InfijoAPosfijo.conviertePostfijo(list));
				String respe = Double.toString(resp);
				Pantalla.setText(respe);
				
			} catch (ExceptionColeccionVacia e) {
				Pantalla.setText("Error logico");
			}
		} else {
			Pantalla.setText("Datos invalidos");
		}

	}

	private void comaActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + ".";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "^";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void ceroActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "0";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void masActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "+";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void tresActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "3";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void dosActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "2";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void unoActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "1";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void menosActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "-";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void seisActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "6";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void cincoActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "5";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "4";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void nueveActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "9";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void sieteActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "7";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void parentesis2ActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + ")";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void parentesis1ActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = expresio + "(";
		Pantalla.setText(expresio);
	}

	private void ACActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = "";
		Pantalla.setText(expresio); // TODO add your handling code here:
	}

	private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {
		expresio = "";
		Pantalla.setText(expresio);
		// TODO add your handling code here:
	}

	private void PantallaTextValueChanged(java.awt.event.TextEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Vista().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton AC;
	private java.awt.TextField Pantalla;
	private javax.swing.JButton cero;
	private javax.swing.JButton cinco;
	private javax.swing.JButton coma;
	private javax.swing.JButton cuatro;
	private javax.swing.JButton div;
	private javax.swing.JButton dos;
	private javax.swing.JButton igual;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JButton mas;
	private javax.swing.JButton menos;
	private javax.swing.JButton mult;
	private javax.swing.JButton nueve;
	private javax.swing.JButton ocho;
	private javax.swing.JButton parentesis1;
	private javax.swing.JButton parentesis2;
	private javax.swing.JButton potencia;
	private javax.swing.JButton seis;
	private javax.swing.JButton siete;
	private javax.swing.JButton tres;
	private javax.swing.JButton uno;
	// End of variables declaration
}
